version: '3'

services:

  app:
    image: phpearth/php:7.3-apache
    volumes:
      - ./:/var/www/localhost/htdocs
    labels:
      - "traefik.http.routers.my-website.rule=Host(`tebe.test`)"
    networks:
    - traefik_default

networks:
  traefik_default:
    external: true
