name: Build & Deploy

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '13.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm dependencies and build JS and CSS
        run: |
          npm install
          npm run build

      - name: Cleanup directory
        run: |
          rm -rf .git .github frontend node_modules
          rm .gitignore *.json *.lock *.yml

      - name: Deploy to server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "."
          target: "/home/tbreusst/public_html/ch.tebe"
